# Generated by Django 3.0.9 on 2020-08-19 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_git', models.URLField(max_length=128)),
                ('project_name', models.CharField(max_length=128)),
                ('explanation', models.CharField(max_length=300)),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
